Repository CESARBR/knot-documentation, pull requests merged in 2019-07, with the labels that each got.

#10 Fix on cloud documentation
  doc/cloud/api/api-authenticator.rst
  doc/cloud/api/api-storage.rst
  doc/cloud/api/api-websocket.rst
Labels: bug, enhancement

#11 Fix indentation on thing samples toctree
  doc/thing/thing-samples.rst
Labels: bug

#20 quick-start: thing: Use Docker as default env
  _static/nrfconnect_add_hex.png
  _static/nrfconnect_add_programmer.png
  _static/nrfconnect_launch_programmer.png
  _static/nrfconnect_select_device.png
  doc/quick-start/qs-guide.rst
Labels: priority: medium

#22 quick-start: gateway: Add set gateway up section
  _static/gateway_setup_cloud.png
  _static/gateway_setup_name.png
  _static/gateway_setup_signin.png
  _static/gateway_setup_wizard.png
  _static/gateway_signin.png
  doc/quick-start/qs-guide.rst
Labels: area: Gateway, area: Quick Start, enhancement, priority: medium

#26 quick-start: setup app: Add configure Thing
  _static/android_gateway_login.png
  _static/android_gateways_connected.png
  _static/android_ot_settings.png
  _static/android_things_unregistered.png
  _static/dk_setup.gif
  _static/dongle_setup.gif
  doc/quick-start/qs-guide.rst
Labels: area: Quick Start
